### ISSUE TITLE
Security Enhancement: Store password inside KeyChain services

### ISSUE THREAD

**Issue by tiankaima** [Life-USTC/Life-USTC#19]
Related Documentation: https://developer.apple.com/documentation/security/keychain_services

**Comment by odeinjul** [comment]
Maybe this one is more related with iOS KeyChain services: https://developer.apple.com/documentation/security/password_autofill/about_the_password_autofill_workflow

**Comment by tiankaima** [comment]
> Maybe this one is more related with iOS KeyChain services: https://developer.apple.com/documentation/security/password_autofill/about_the_password_autofill_workflow

https://developer.apple.com/documentation/xcode/supporting-associated-domains

kinda mis-understanding happened here, I believe

By storing password in keychain service, we would have the security of the password managed by the system, so that when user doing dangerous stuff like backing up their phone without a password (or hackers dumping the whole `kCFPreferencesAnyUser` file), the password doesn't just show up in plain text with the key `passportPassword` next to it.

Implementing autofill with the system password manager is a great feature to work on, to implement that, however, you'll need to put a file on the website associating the app id to indicate that the app developer owns the website.. That's something we could discuss with ppl at ustcnet later this year...

**Comment by tiankaima** [comment]
To help you understand what I mean, go check **KeyChain Access** on your mac, you'll find credentials used by apps listed here so that even a hacker is granted regular user access, they don't get to just dump the password out without root access, but the app still have the ability to read from KeyChain without root

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/91816094/235637100-bf197a9b-f437-4778-86d4-f98d95c98429.png">

**Comment by tiankaima** [comment]
funny, this actually enables the app to automatically fill the password in case of reinstall.
