### ISSUE TITLE
Incorrect behavior with Keychain Access Group

### ISSUE THREAD

**Issue by tiankaima** [Life-USTC/Life-USTC#44]
Introduced in #19 #36, Keychain is a secure way to store and access username and password.

To share the credentials between main app and widget bundle, the fix is introduced in #42, but seems not to be working properly

**Comment by tiankaima** [comment]
A search on GitHub brings this:
https://github.com/team-yello/YELLO-iOS/blob/bc79a3cc0e0cb355dc8c0207407754a2d63dca53/YELLO-iOS/YELLO-iOS/Global/KeychainHandler.swift#L20

**Comment by tiankaima** [comment]
try out https://github.com/auth0/SimpleKeychain/blob/master/EXAMPLES.md

**Comment by odeinjul** [comment]
Any more precise description about the _Incorrect behavior_ ？

**Comment by tiankaima** [comment]
> Any more precise description about the _Incorrect behavior_ ？

In #36 , a `KeychainWrapper.swift` file is introduced to access keychain in a more convenient way

But that file is shared between the main app target and the widget(declared as app widget), the app would then store the username&password inside the app’s `Keychain Access Group` (not accessible by other apps), which the widget can’t access.

The fix for this is inside #42 , (which wasn’t targeted for this, but was still noticed)

According to apple’s documentation, since we’re already sharing an `App Group`, a `Keychain Access Group` identified as `group.dev.tiankaima.life-ustc` should already be created (and accessible by both executables), but the reality is `KeychainWrapper.swift` won’t register the keychain access group and would throw error every time.

To be clear, I did test the pr locally before pushing, it was working back then. I’m not sure what happened afterwards, might be something related to signing, I suppose.

**Comment by tiankaima** [comment]
Using a standalone package and fixes everything... too lazy for me to actually debug the reason behind this
